# Generated by Django 4.0.5 on 2022-06-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_remove_user_admin_remove_business_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hood',
            name='description',
        ),
    ]
